import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync } from 'node:fs';

/**
 * The guardrails that stop a theme from being a vibe.
 *
 * The design encodes an architecture, not just a palette: the graph canvas is the darkest
 * surface so lit work is the brightest thing on screen, planned structure sits below
 * materialized work, and the accent is reserved for action. A theme is only allowed to move
 * hue and chroma. Hand-edit one surface value and the ladder breaks silently — nothing
 * looks broken, the design just stops meaning anything. These tests catch that.
 */
const css = readFileSync(new URL('../src/workspace.css', import.meta.url), 'utf8').replaceAll(
  '\r',
  '',
);

function themeBlock(name) {
  const head = name === 'sage' ? ':root,' : `[data-theme='${name}']`;
  const at = css.indexOf(head);
  assert.ok(at >= 0, `theme block for ${name} must exist`);
  const body = css.slice(css.indexOf('{', at) + 1, css.indexOf('\n}', at));
  const tokens = {};
  for (const line of body.split('\n')) {
    const match = line.match(/--([\w-]+):\s*(#[0-9a-f]{6});/);
    if (match) tokens[match[1]] = match[2];
  }
  return tokens;
}

const toLinear = (hex) => {
  const channel = (v) => (v <= 0.04045 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4);
  return [1, 3, 5].map((i) => channel(parseInt(hex.slice(i, i + 2), 16) / 255));
};
/** WCAG relative luminance — the right measure for contrast and for surface ordering. */
const relLum = (hex) => {
  const [r, g, b] = toLinear(hex);
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
};
/**
 * OKLab lightness — the right measure for "same step on the ladder".
 * The themes are generated by holding this constant and moving only hue and chroma, so
 * this is the invariant to assert. Relative luminance is NOT interchangeable here: a blue
 * and a green at identical perceptual lightness differ in relative luminance by design.
 */
const okLightness = (hex) => {
  const [r, g, b] = toLinear(hex);
  const l = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b);
  const m = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b);
  const s = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b);
  return 0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s;
};
const ratio = (a, b) => {
  const [x, y] = [relLum(a), relLum(b)].sort((p, q) => q - p);
  return (x + 0.05) / (y + 0.05);
};

/** The roles allowed to leave the surface hue, and so to run into the gamut boundary. */
const ACCENTS = new Set([
  'accent-soft', 'accent-line', 'accent-line-2', 'accent-text-dim', 'accent-text',
  'accent-text-2', 'accent', 'accent-bright', 'accent-ink', 'edge-done',
]);

const DARK = ['sage', 'slate', 'ember', 'mono'];
const ALL = [...DARK, 'daylight'];

test('every dark theme is the same luminance ladder, only re-hued', () => {
  const base = themeBlock('sage');
  assert.ok(Object.keys(base).length > 30, 'the base theme must actually parse');
  for (const name of DARK.slice(1)) {
    const theme = themeBlock(name);
    assert.deepEqual(
      Object.keys(theme).sort(),
      Object.keys(base).sort(),
      `${name} must define exactly the same tokens`,
    );
    for (const [token, value] of Object.entries(base)) {
      // Surfaces hold the ladder exactly. Accents deliberately run higher chroma, and a
      // saturated hue at the accent's lightness can fall outside sRGB; clamping back into
      // gamut shifts lightness slightly. That is a known, bounded cost of wanting a vivid
      // accent — it is allowed a wider tolerance, not an unbounded one.
      const limit = ACCENTS.has(token) ? 0.012 : 0.006;
      const drift = Math.abs(okLightness(theme[token]) - okLightness(value));
      assert.ok(
        drift < limit,
        `${name}.${token} left the ladder (${value} -> ${theme[token]}, d=${drift.toFixed(4)})`,
      );
    }
  }
});

test('the canvas stays the darkest surface, and the accent outshines a completed edge', () => {
  for (const name of DARK) {
    const theme = themeBlock(name);
    for (const surface of ['rail', 'bg', 'panel', 'panel-2', 'raised-panel', 'node-fill']) {
      assert.ok(
        relLum(theme.canvas) < relLum(theme[surface]),
        `${name}: the canvas must be darker than ${surface}`,
      );
    }
    assert.ok(
      relLum(theme.accent) > relLum(theme['edge-done']),
      `${name}: the accent must outshine a completed edge`,
    );
  }
});

test('daylight inverts the ground but keeps the rule underneath it', () => {
  const day = themeBlock('daylight');
  // On a light ground "darkest" flips to "most inked", so planned must be LIGHTER than text.
  assert.ok(
    relLum(day['node-planned-text']) > relLum(day.text),
    'planned structure must stay recessive against executed work',
  );
  assert.ok(
    relLum(day.canvas) < relLum(day.panel),
    'the canvas stays quieter than the panels around it',
  );
});

test('every theme meets its contrast floors on the pairs that carry text', () => {
  const pairs = [
    ['text', 'bg', 4.5],
    ['text', 'panel', 4.5],
    ['text', 'node-fill', 4.5],
    ['secondary', 'panel', 4.5],
    ['quiet', 'rail', 4.5],
    ['accent-text', 'panel', 4.5],
    ['accent-ink', 'accent', 4.5],
    ['node-planned-text', 'node-planned-fill', 3],
  ];
  for (const name of ALL) {
    const theme = themeBlock(name);
    for (const [fg, bg, min] of pairs) {
      const value = ratio(theme[fg], theme[bg]);
      assert.ok(value >= min, `${name}: ${fg} on ${bg} is ${value.toFixed(2)}, needs ${min}`);
    }
  }
});

test('no colour literal escapes the theme blocks', () => {
  let inBlock = false;
  const strays = [];
  for (const [index, line] of css.split('\n').entries()) {
    if (/^:root|^\[data-theme/.test(line)) inBlock = true;
    else if (inBlock && line.startsWith('}')) inBlock = false;
    if (!inBlock && /#[0-9a-fA-F]{3,8}\b/.test(line)) strays.push(`${index + 1}: ${line.trim()}`);
  }
  assert.deepEqual(strays, [], 'every colour must come from a token, or a theme half-lands');
});
